### ISSUE TITLE
Uncaught TypeError: Invalid value used as weak map key

### ISSUE THREAD

**Issue by darrylcousins** [bikeshaving/crank#236] opened 2022-08-04 06:35 UTC
Hi Brian,

I was surprised that a crank app suddenly failed with a new Shopify theme. Removing the theme javascript solved the problem but of course is not the solution. The app is compiled with [Vite](https://vitejs.dev) and minified. Resulting in a show stopping error and the app not rendering:

```
boxesapp.js?v=160012563599259014851659593001:1 Uncaught (in promise) TypeError: c.then is not a function
    at Ot (boxesapp.js?v=160012563599259014851659593001:1:5435)
    at _e (boxesapp.js?v=160012563599259014851659593001:1:3873)
    at Ot (boxesapp.js?v=160012563599259014851659593001:1:5373)
    at _e (boxesapp.js?v=160012563599259014851659593001:1:3873)
    at oe (boxesapp.js?v=160012563599259014851659593001:1:9132)
    at boxesapp.js?v=160012563599259014851659593001:1:11469
    at async Promise.all (index 0)
    at async Object.fn [as init] (boxesapp.js?v=160012563599259014851659593001:7:10767)
```

Recompiling and disabling minify; the app will load correctly but with errors in the inspector:

```
Uncaught TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at addEventListener (boxesapp.js?v=181202394000030643281659593075:993:20)
    at Function.bindReady (jquery.min.js:2:9844)
    at init.ready (jquery.min.js:2:8340)
    at new init (jquery.min.js:2:7732)
    at e (jquery.min.js:2:6172)
    at jquery.min.js:2:19170
    at jquery.min.js:2:21280
    at jquery.min.js:4:29596
```

Which in boxesapp is at:

```
const listenersMap = /* @__PURE__ */ new WeakMap();
function addEventListener(ctx, type, listener, options) {
  let listeners;
  if (listener == null) {
    return;
  } else {
    const listeners1 = listenersMap.get(ctx);
    if (listeners1) {
      listeners = listeners1;
    } else {
      listeners = [];
      listenersMap.set(ctx, listeners); // * error here
    }
  }
```

So I'm wondering if crank can catch this error and fail silently if this is appropriate? Or am I barking at the wrong tree? I only post this here because it seems to me that this will pop up for others when jQuery is present.

I did spend quite a bit of time trying to adjust my code to eliminate the error but without success. I defer to better minds than my own.

Kind regards,
Darryl Cousins

**Comment by brainkim** [comment] 2022-08-04 17:58
Hey Darryl! Firstly, as always, I am sorry about the bug and I am looking into this immediately. 

Unfortunately, I might need a little more information. The second error could indicate that the receiver is lost or changed to Crank’s `addEventListener()` method. In other words, somehow your code is calling `this.addEventListener()`, where `this` is the Crank context, but it’s being invoked as a plain function and not a method.

```js
// inside a Crank component
const addEventListener = this.addEventListener;
// the following line throws because `this` is not referenced in the invocation.
addEventListener("event", listener);
```

You can use `Function.prototype.bind` to make sure the `addEventListener` method is bound correctly.

```js
// inside a Crank component
const addEventListener = this.addEventListener.bind(this);
addEventListener("event", listener); // doesn’t throw anymore
```

The error which is currently emitted about weakmaps is a poor user experience, and we probably want to print a better error in this situation.

In the function you posted above, I would love to check what the `ctx` argument is. My guess is that it’s going to be `undefined`. That would be the first thing I checked with a debugger or a logging statement if you can modify that function, or instrument it with a DevTools breakpoint.

I would also double-check to make sure you were always calling `addEventListener` with the Crank context as receiver. However, this wouldn’t explain why the crash only happens only when third party JavaScript is added.

Another possibility is that the `ContextImpl`, which is the internal object which is used to hide context internals, has been lost. I have no idea how this would happen and I would be very interested to find out why. I’m also concerned about two different errors being emitted in minification versus development.

Perhaps you could share the Shopify theme or library that you were using, so that I could try to debug it myself? I also found this description of jQuery’s `bindReady()` function (https://programmer.group/detailed-explanation-of-jquery-source-code-analysis-ready-event.html), but I’m not seeing how anything there could cause the crash you described.

Again, I’m sorry about the bug and hope to have it fixed soon!

**Comment by darrylcousins** [comment] 2022-08-05 00:01
Hi Brian,

Thanks for your prompt and detailed reply. I've done some more digging. I built a small app into which I loaded as much of the javascript from the shopify theme as I could find in there (there's a lot!). But I couldn't reproduce the problem.

As a further note I'm using the same theme on another development shop without any problems although it should have all the same code (thought by definition clearly does not). Shopify is an environment of plugins and apps so all sorts of code is running.

I dropped a console call in the crank code:

```
const listenersMap = /* @__PURE__ */ new WeakMap();
function addEventListener(ctx, type, listener, options) {
  console.log(ctx, listener);  //                             <---- here
  let listeners;
  if (listener == null) {
    return;
  } else {
    const listeners1 = listenersMap.get(ctx);
```
Noting that an error is only thrown when `listener === false` (see screenshot below) I tried checking for that by:

```
const listenersMap = /* @__PURE__ */ new WeakMap();
function addEventListener(ctx, type, listener, options) {
  console.log(ctx, listener);
  let listeners;
  if (listener == null || !Boolean(listener)) {   //  <---- here
    return;
  } else {
    const listeners1 = listenersMap.get(ctx);
```

And the error went away. I obviously don't know of any side effects that this may cause to crank, I leave that with you.

Just some thoughts.

Yours sincerely,
Darryl Cousins

![addEventListenerError](https://user-images.githubusercontent.com/93854/182974080-b721e1c5-b221-458a-9ea4-4ded216340d5.png)

![addEventListener](https://user-images.githubusercontent.com/93854/182971322-6383b097-39cd-4204-a4bf-153b30c382f6.png)

**Comment by darrylcousins** [comment] 2022-08-08 04:35
Hi Brian,

I still struck the same problem despite my ```!Boolean(listener)``` hack.

What works better for me is:

```
const listenersMap = /* @__PURE__ */ new WeakMap();
function addEventListener(ctx, type, listener, options) {
  console.log(ctx, listener);
  let listeners;
  if (listener == null || !Object.hasOwnProperty(ctx, "ctx")) {   //  <---- here
    return;
  } else {
    const listeners1 = listenersMap.get(ctx);
  ...
```

Though I suppose a ```typeof ctx === ContextImp``` or similar may be better?

Just a thought.

Sincerely,
Darryl Cousins

**Comment by brainkim** [comment] 2022-08-08 20:28
Okay. Happy Monday! Thank you for the additional information and patience. Based on the screenshot in https://github.com/bikeshaving/crank/issues/236#issuecomment-1205894064, I think I might have a better understanding of what might be happening. My guess is that the build tool you’re using is concatenating the files together in such a way that the `addEventListener()` function is exposed outside the module scope of Crank, and third-party library code is calling that function, under the assumption that it is the global `window.addEventListener()`. This would explain the lines like `"pagehide", undefined` and `"load", false`, so the weakmap call is vomiting because it’s being called with string keys. 

While this is technically an upstream issue (vite), I think there are a couple mitigations I can do on the library end, including re-inlining the function (dunno why I defined it separately and I’ll look through the code), and adding the checks you suggested.

Should be fixed in https://github.com/bikeshaving/crank/pull/238, which I’ll try to have a release for by the end of today, California time. I’m fixing the bug blind, but I’m reasonably sure of what’s going on. The one thing is if we want to be good users and report the bug upstream, but I don’t have the full context to create a reproduction there.

**Comment by darrylcousins** [comment] 2022-08-08 22:29
Hi Brian,

Thanks for your reply. I have installed the [fix-eventtarget-errors](https://github.com/bikeshaving/crank/tree/fix-eventtarget-errors) branch and the problem is fixed. Unminified passes without errors as does the minified bundle.

Your summary of the problem is how I see it too. I think you can close this.

Many thanks.
Darryl Cousins

**Closed** 2022-08-08 22:36 UTC
Labels: bug
